# Generated by Django 5.0.4 on 2024-04-23 07:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='level',
            field=models.ForeignKey(limit_choices_to={'active': 1}, on_delete=django.db.models.deletion.CASCADE, to='www.level', verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', '手机号格式错误')], verbose_name='手机号'),
        ),
    ]
