# Generated by Django 4.2.5 on 2024-04-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_alter_customer_level_alter_customer_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(db_index=True, max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'active': 1}, on_delete=django.db.models.deletion.CASCADE, to='www.customer', verbose_name='客户'),
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=32, verbose_name='用户名')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.depart', verbose_name='部门')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='hbs',
            field=models.ManyToManyField(to='www.hobby', verbose_name='爱好'),
        ),
    ]
